### ISSUE TITLE
Not work when textview is in scrollview/multiple horizontal recycleview in same screen

### ISSUE THREAD

**Issue by sagargadani** [Rajagopalr3/CustomizedTextView#3]
Not work when textview is in scrollview/multiple horizontal recycleview in same screen.

Inside vertical scroll does not show read more option.

In horizontal recycle view some time it come , some times not

**Comment by Rajagopalr3** [comment]
Sorry for replying late, reported issues is fixed in v1.6 now you can able to create textview by 
 programmatically. let me know if u are facing any issue on this?
